main = "src/index.ts"
usage_model = "bundled"
compatibility_date = "2022-04-27"
minify = true
tsconfig = "./tsconfig.json"
workers_dev = false


[env.dev]
name = "worker-one-dev"
services = [
  { binding = "WORKERTWO", service = "worker-two-dev" },
]

[env.dev.durable_objects]
bindings = [{ name = "WORKERONE_DO", class_name = "WorkerOneDO" }]